/*! 
 A Math Timeline for diving into the history and evolution of maths. Very useful for teachers to explain the progress of maths in a ludic way.
 It's written in Rust and actix-web for the server and React.js for the frontend.
*/

#![warn(missing_docs)]

/// A module with the model DB
pub mod models;
/// The DB schema (auto-generated by Diesel)
pub mod schema;